### Listar todos os usuarios
GET http://localhost:3100/users

### Retornar o usuário de id 123
GET http://localhost:3100/users/66d641c2848fd9ef4679a46b

### Criar um novo usuário
POST http://localhost:3100/users
Content-Type: application/json

{
    "login": "admin",
    "senha": "admin"
}

### Atualizar o usuário de id 123
PUT http://localhost:3100/users/66d641c2848fd9ef4679a46b
Content-Type: application/json

{
    "login": "admin1",
    "senha": "admin1"
}

### Excluir o usuário de id 123
DELETE http://localhost:3100/users/66d641c2848fd9ef4679a46b